version: '3.7'

services:
  postgres:
    env_file:
      - .env
    image: 'postgres:latest'
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME:-username}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-db}
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
    driver: local
